### ISSUE TITLE
Missing meet

### ISSUE THREAD

**Issue by jakeyb43** [sstangl/openpowerlifting#1119]
There was a meet in Salt Lake City Utah during FItcon called IPL World Cup. The meet director was Chris McGrail. Lots of big lifters there

**Comment by sstangl** [comment]
That meet is ID 1089 on USPA's list here -- http://uspa.net/competition_results.html

As of this writing they have not posted results for it, so there is no way for us to include the results yet.

Because this meet is USPA, we'll notice almost immediately when the results are up, and will import them shortly after. So I'll close this bug for the moment, because the meet will be added as soon as possible without needing further reminding.
