### ISSUE TITLE
APF results from 2017 - missing meet

### ISSUE THREAD

**Issue by kpmtnman** [sstangl/openpowerlifting#1265]
https://worldpowerliftingcongress.com/wp-content/uploads/2017/07/2017-Show-of-Strength-Full-Meet-Results.pdf

**Comment by sstangl** [comment]
Are you sure it's missing? It looks like this meet: http://beta.openpowerlifting.org/m/apf/1716

**Comment by kpmtnman** [comment]
Found it. Info is incomplete on my listing. Bodyweight did not input, thus
no Wilks.

Kevin Pitman

**Comment by sstangl** [comment]
What happened is that the meet director did not record anyone's bodyweight -- just their weight class.

So all the other lifters got assigned the maximum possible bodyweight allowed by their class.

Unfortunately, since you were SHW, there is no such maximum possible bodyweight, so not even a pessimal bodyweight can be reported.

If you'd like to have your bodyweight reported, the best way to do so is to contact the meet director. If the meet director contacts us, we can fill it in. Sorry about that :(

**Comment by kpmtnman** [comment]
I get it. That meet was last year. Let's see if I can improve that number
make the list this year!

Thanks.

Kevin Pitman
