### ISSUE TITLE
Malanichev's 2513.3 lb total is missing his age, weight, and wilks score from the meet

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#131]
Malanichev's 2513.3 lb total is missing his age, weight, and wilks score from the Big Dogs Pro Raw meet

**Comment by sstangl** [comment]
Big Dogs is a special meet: it's only for SHW lifters, and they make it a point to not record the lifters' bodyweights. The competition is done entirely by Total. Since the bodyweights are unknown, the Wliks also can't be calculated.

It's unfortunate, but that's how the meet is set up. Big Dogs 2 is coming up soon!

**Comment by TrystanOakley** [comment]
Oh of course I completely forgot
