### ISSUE TITLE
Jaclyn Do competed in sleeves, not wraps

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#132]
Jaclyn Do competed in sleeves, not wraps at her RPS meet on 5-6-2017. Proof is on her instagram https://www.instagram.com/jaclyndo/ and I know her personally

**Comment by sstangl** [comment]
Thanks! Pretty often it happens that a lifter competes in a division that allows "sleeves or wraps," and chooses to compete in sleeves. Without evidence otherwise, our only option is to mark that entire division as "Wraps." This happens all the time for the SPF in particular.

Also, now is a good time to point out that if you go to the meet page, there's an "Edit Meet" button in the top-right corner! If you look at the change I made above, you can make that same change yourself in the future.

**Comment by TrystanOakley** [comment]
Thank you. I am still trying to figure out how to edit meets as of now but will get right on that. My mistake.
