### ISSUE TITLE
Lifter Request to add meet GPCGB British Championships 

### ISSUE THREAD

**Issue by TrystanOakley** [sstangl/openpowerlifting#549]
Held on November 11 2017
http://www.neilside.co.uk/index.php?showcomp=411
Nobody can find the results straight from the GPC but it is for lifter wynter addams with a 1135 lb total at 67.5 kg bw.

**Comment by TrystanOakley** [comment]
http://www.worldgpc.com her meet is somewhere here. They said it was at the GPCGB British Championships but I can't seem to find it

**Comment by sstangl** [comment]
The owner of Neilside is hostile to our project, to my understanding. We should not use them as a data source, and we basically should never look at their website.

**Comment by TrystanOakley** [comment]
Hostile? Why? I thought we were going to approach him about working
together?

She contacted the Fed and is getting the results

**Comment by sstangl** [comment]
From the fed, sure -- I just mean that we shouldn't use Neilside as a data source, because the person who runs that site would really, really not like that. Although I think that legally there is no protection to that data, since they are about factual information, I'd still rather not piss him off.

**Comment by TrystanOakley** [comment]
Oh well. Time to add all of GPCGB out of spite

**Comment by JoWhiteley** [comment]
This can close I think.  gpc-gb/1701
